/**
 * Maps a Mercado Livre product URL (as returned by fetchMercadoLivreDeals)
 * to the affiliate short link the user wants visitors sent to instead.
 *
 * These are pre-generated per-product links (meli.la — Mercado Livre's own
 * affiliate program shortener). Each one only works for the exact product
 * it was created for, so this is a snapshot tied to one catalog fetch, not
 * something that can be derived automatically. As /ofertas rotates and new
 * products appear, they won't have an entry here — lookupAffiliateUrl()
 * falls back to the plain Mercado Livre link for those rather than risk
 * sending a visitor to the wrong product through a stale mapping.
 */
const PRODUCT_TO_AFFILIATE_URL: [productUrl: string, affiliateUrl: string][] = [
  [
    "https://www.mercadolivre.com.br/creatina-monohidratada-500g-growth-supplements-sem-sabor-em-po/p/MLB66637233",
    "https://meli.la/2wT1dEs",
  ],
  [
    "https://www.mercadolivre.com.br/smart-tv-lg-uhd-ai-ua75-50-polegadas-hdr10-pro-processador-7-ai-ger8-webos-25/p/MLB53201474",
    "https://meli.la/1qbVDtC",
  ],
  [
    "https://www.mercadolivre.com.br/celular-samsung-galaxy-a07-256gb-8gb-camera-50mp-tela-67-protecao-ip54-processador-6nm-violeta/p/MLB54964804",
    "https://meli.la/2fLM3dT",
  ],
  [
    "https://www.mercadolivre.com.br/notebook-acer-aspire-5-a515-45-r2a3-amd-ryzen-5-windows-11-home-8gb-512gb-ssd-156-full-hd/p/MLB22246671",
    "https://meli.la/2wHmkWp",
  ],
  [
    "https://www.mercadolivre.com.br/monitor-portatil-156-tela-externa-hdr-ips-1080p-ultrafino/up/MLBU2939238991",
    "https://meli.la/25JZjuF",
  ],
  [
    "https://www.mercadolivre.com.br/kerastase-chroma-absolu-fondant-cica-chroma-condicionador-cuidado-de-color-200ml/p/MLB35478376",
    "https://meli.la/1FQWaN8",
  ],
  [
    "https://www.mercadolivre.com.br/creatina-creapure-250g-growth-supplements-sem-sabor-em-po-suplemento-esportivo/p/MLB18726360",
    "https://meli.la/1QTJcaS",
  ],
  [
    "https://www.mercadolivre.com.br/smart-tv-43-led-full-hd-ultrafina-sem-bordas-3-hdmi-2-usb-controle-remoto-multifuncional-wifi-bluetooth-efl-43sx800fd/p/MLB54964776",
    "https://meli.la/11Q6zGc",
  ],
  [
    "https://www.mercadolivre.com.br/kit-2-refletor-super-led-400w-ip67-holofote-bivolt-prova-dagua-branco-frio-6500k-preto/p/MLB57490176",
    "https://meli.la/2kZ9AjX",
  ],
  [
    "https://www.mercadolivre.com.br/camera-inteligente-resistente-a-chuva-e-poeira-im7-s-branca-intelbras/p/MLB40230034",
    "https://meli.la/2JiwGn8",
  ],
  [
    "https://www.mercadolivre.com.br/conj-de-panelas-8-pecas-ceramic-life-smart-plus-vanilla-brinox/p/MLB32717965",
    "https://meli.la/1dMmF1y",
  ],
  [
    "https://www.mercadolivre.com.br/bicicleta-spinning-sevenfit-eps-988-com-volante-de-6-kg-e-computador/p/MLB42978348",
    "https://meli.la/2LmyAXd",
  ],
  [
    "https://www.mercadolivre.com.br/mochila-jiesipote-prova-dagua-reforcada-expansivel-cor-preto/p/MLB74678961",
    "https://meli.la/2QCgBWF",
  ],
  [
    "https://www.mercadolivre.com.br/kit-10-pote-de-vidro-marmita-hermetico-640ml-freezer-fitness-rishon/p/MLB63904966",
    "https://meli.la/2oJFsjs",
  ],
  [
    "https://www.mercadolivre.com.br/compressor-portatil-car-air-pump-digital-com-visor-para-carro-moto-bike-calibrador-de-pneu-multifuncional/p/MLB57468821",
    "https://meli.la/1uUixFB",
  ],
  [
    "https://www.mercadolivre.com.br/conjunto-de-panelas-antiaderente-10-pecas-coffee-cappuccino-imperial/p/MLB62276281",
    "https://meli.la/2WWLcL1",
  ],
  [
    "https://www.mercadolivre.com.br/smart-tv-32-philco-p32vik-roku-led-dolby-audio-hdr-wi-fi-110220v/p/MLB63036814",
    "https://meli.la/1W396AE",
  ],
  [
    "https://www.mercadolivre.com.br/creatina-1kg-suplemento-monohidratada-em-po-100-pura-soldiers-nutrition/p/MLB18725310",
    "https://meli.la/2VaM2av",
  ],
  [
    "https://www.mercadolivre.com.br/kit-10-pote-de-vidro-marmita-hermetico-370ml-freezer-fitness-rishon/p/MLB66060206",
    "https://meli.la/1StELiX",
  ],
  [
    "https://www.mercadolivre.com.br/mochila-masculina-impermeavel-reforcada-com-capacidade-ampliada-de-30-42l-adequada-para-portatil-viagens-diarias-cor-preta/p/MLB75625924",
    "https://meli.la/23ByLrr",
  ],
  [
    "https://www.mercadolivre.com.br/espelho-100x50-organico-corpo-inteiro-grande-moldura-caramelo/p/MLB55868679",
    "https://meli.la/2Vj6y8u",
  ],
  [
    "https://www.mercadolivre.com.br/kit-2-cameras-seguranca-ip-interna-externa-wifi-icsee-infravermelho-prova-dagua-hw/p/MLB46836439",
    "https://meli.la/2dVTgQY",
  ],
  [
    "https://www.mercadolivre.com.br/notebook-asus-vivobook-15-m1502-amd-ryzen-7-8-gb-ram-512-gb-ssd-keepos-linux-cool-silver-m1502ya-nj611/p/MLB49089309",
    "https://meli.la/1kWWtdG",
  ],
  [
    "https://www.mercadolivre.com.br/escova-modeladora-de-ions-negativosde-38mm9-ajustes-de-temperaturaliso-oucacheadosecagem-rapidatecnologia-deaquecimento-ptcntc-tecnologiacuidado-capilar-com-ions-negativoscachos-duradouros/p/MLB62631049",
    "https://meli.la/1dRFPER",
  ],
  [
    "https://www.mercadolivre.com.br/hipercalorico-dark-mass-3kg-chocolate-branco-c-morango-dark-lab/p/MLB19451610",
    "https://meli.la/32AbWxJ",
  ],
  [
    "https://www.mercadolivre.com.br/kit-10-potes-vidro-370ml-hermetico-marmita-forno-refratario-star-house/p/MLB53222545",
    "https://meli.la/2anMEox",
  ],
  [
    "https://www.mercadolivre.com.br/jbl-boombox-4-caixa-de-som-bluetooth-ip68-34h-playtime/p/MLB55237000",
    "https://meli.la/2ysUnVR",
  ],
  [
    "https://www.mercadolivre.com.br/tp-link-tapo-c500-camera-de-seguranca-wifi-1080p-360-colorida-ip65/p/MLB23037572",
    "https://meli.la/1McSKPR",
  ],
  [
    "https://www.mercadolivre.com.br/o-boticario-her-code-kit-presente-3-itens/up/MLBU3825005580",
    "https://meli.la/1XHXzyW",
  ],
  [
    "https://www.mercadolivre.com.br/notebook-samsung-galaxy-book4-intel-u300-120-ghz-ate-44ghz-8-mb-l3-cache-windows-11-home-8gb-256gb-ssd-uhd-graphics-156-full-hd-led-155kg/p/MLB40347107",
    "https://meli.la/33ucHsn",
  ],
  [
    "https://www.mercadolivre.com.br/creatina-monohidratada-250g-growth-supplements-sem-sabor-em-po/p/MLB19603205",
    "https://meli.la/18NsGxd",
  ],
  [
    "https://www.mercadolivre.com.br/smart-tv-tcl-32-polegadas-fhd-qled-s5k-wifi-bluetooth-google-tv-2-hdmi-hdr10-dolby-audio-32s5k/p/MLB49197371",
    "https://meli.la/213Xqnk",
  ],
  [
    "https://www.mercadolivre.com.br/kit-travesseiro-50x70cm-buddemeyer-toque-de-pluma-algodao-branco-2-pecas/p/MLB36540228",
    "https://meli.la/1GkfgV2",
  ],
  [
    "https://www.mercadolivre.com.br/smartphone-samsung-galaxy-a36-5g-256gb-8gb-ram/p/MLB47111905",
    "https://meli.la/2GKLcDy",
  ],
  [
    "https://www.mercadolivre.com.br/tp-link-tapo-c320ws-camera-de-seguranca-wifi-2k-qhd-colorida-ip66/p/MLB19693785",
    "https://meli.la/18AewcY",
  ],
  [
    "https://www.mercadolivre.com.br/cadeira-escritorio-ergonomica-genebra-b500-luvinco-cor-preto-com-suporte-lombar-estofado-mesh/p/MLB46220740",
    "https://meli.la/1o9ZAF2",
  ],
  [
    "https://www.mercadolivre.com.br/jogo-de-panelas-4pcs-solar-aco-inox-tramontina/p/MLB32488860",
    "https://meli.la/2YPxyHM",
  ],
  [
    "https://www.mercadolivre.com.br/smart-tv-roku-tv-50-7045-4k-uhd-aoc-bivolt/p/MLB51202548",
    "https://meli.la/2F8pNkA",
  ],
  [
    "https://www.mercadolivre.com.br/smartphone-motorola-moto-g15-256gb-12gb-4gb-ram8gb-ram-boost-e-camera-50mp-com-ai-e-night-vision-bateria-de-5200-mah-tela-fhd-67-com-superbrilho-nfc-grafite/p/MLB44665473",
    "https://meli.la/2eeXvBa",
  ],
  [
    "https://www.mercadolivre.com.br/parafusadeira-furadeira-de-impacto-profissional-sem-fio-48v/up/MLBU3899578757",
    "https://meli.la/1RwMbkX",
  ],
  [
    "https://www.mercadolivre.com.br/conjunto-10-potes-vidro-organizadores-de-cozinha-multiuso-transparente/p/MLB68847931",
    "https://meli.la/1L3pZ7v",
  ],
  [
    "https://www.mercadolivre.com.br/principia-kit-gl-02-gh-01-ps-01-todo-tipo-de-pele-dianoite/p/MLB52069535",
    "https://meli.la/2JzKng4",
  ],
  [
    "https://www.mercadolivre.com.br/smart-tv-un55u8100fgxzd-crystal-55-4k-preto-samsung-bivolt/p/MLB50308413",
    "https://meli.la/2SUsqBh",
  ],
  [
    "https://www.mercadolivre.com.br/cadeira-de-escritorio-ergonomica-fivdaily-c600-preta-com-apoio-de-cabeca-e-suporte-lombar/p/MLB63029755",
    "https://meli.la/2in8EA9",
  ],
];

const AFFILIATE_URL_BY_PRODUCT_URL = new Map(PRODUCT_TO_AFFILIATE_URL);

export function lookupAffiliateUrl(productUrl: string): string {
  return AFFILIATE_URL_BY_PRODUCT_URL.get(productUrl) ?? productUrl;
}
